import Head from 'next/head'
import DPOne from '../components/DPOne';
import DPTwo from '../components/DPTwo';
import NavHead from '../components/NavHead';
import NavFooter from '../components/NavFooter';

export default function DetailProduct() {
    return (
      <div>
        <Head>
          <title>Detail Product</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <NavHead />
        <DPOne />
        <DPTwo />
        <NavFooter />
      </div>
    )
  }
  