import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import NavHead from '../components/NavHead';
import SectionOne from '../components/SectionOne';
import NavFooter from '../components/NavFooter';
import SectionTwo from '../components/SectionTwo';
import SectionThree from '../components/SectionThree';
import SectionFour from '../components/SectionFour';
import SectionFive from '../components/SectionFive';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavHead />
      <SectionOne />
      <SectionTwo />
      <SectionThree />
      <SectionFour />
      <SectionFive />
      <NavFooter />
    </div>
  )
}
